### ISSUE TITLE
Suggested addons

### ISSUE THREAD

**Issue by benjaboyy** [electromuis/stepmania-dlm#1]
Would love to see the following features added.

- A tab for Noteskins and maybe even Themes

- This is a bigger one, if you can have a account on DML and you log in elsewhere you can automatically download you're collection. This only works when there is enough demand for it.

- An Easter egg

**Comment by RodentVienna** [comment]
hi electromuis, I'd like to get engaged in a direct conversation about your awesome stuff hosted on github in regards to stepmania.  what would be the best way to get in touch? Facebook chat (Rodent.Vienna)? Discord (RodentVienna#4981)? Thank you!

**Comment by electromuis** [comment]
@benjaboyy ill add a big max300sows440dck somewhere ok?
